### PR TITLE
Update scripts for AWS SDK 3

### PR DESCRIPTION
**Pull request by augiadam**
Updated files for AWS SDK 3, the .dll files are now separated for the AWSSDK.dll

### CODE REVIEW

**Comment by noahlh** [comment]
Thank you so much for creating this pull request!  Is there a reason you closed?  I'm happy to merge whenever it's ready.

**Comment by dms2015** [comment]
This worked great!!  Thanks... fixed all of my other issues.  However, I am still getting a call depth overflow for position 124 in the utilities.ps1 file.  When I researched this error, first, it stated the version of PS under 3 could receive this error.  I have version 3 so other issues pertain to using a "while"  instead of "if" statement.  I don't want to change this script unless I really understand where this error is coming from.  It seems to be getting stuck in a loop.  This seems to be my last error and everyone was so helpful.  Could anyone help me with this also?  

From AWSUtilities.ps1:
Position 124 =  WriteToLog "$function : $exception" -isException $true

This is the messages I am getting below:
 --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(
IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext ex
ecutionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executio
nContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext execu
tionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executio
nContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext execu
tionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext execu
tionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext 
executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext execut
ionContext)
   at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest req
uest, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller)
   at CallSite.Target(Closure , CallSite , Object , Object )
 WriteToLog : System.NotSupportedException: Specified method is not supported.
   at System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(Comman
dParameterInternal argument, String parameterName, Type toType, ParameterCollect
ionTypeInformation collectionTypeInfo, Object currentValue)


It keeps then looping at the WriteToLog section of that message and then goes into a call depth overflow.  
I created the log file as in the instructions and it is there - just an fyi.

**Comment by augiadam** [comment]
Hi guys,

Glad it helped. I tested the scripts again with my changes and I was getting an error for the methods that it was calling. I wanted to test it more before I committed it again. I'd like to make sure that it will work properly :)

Thanks,

Adam.

**Comment by dms2015** [comment]
Thank you so much, Adam for looking into this!!!

**Pull request closed without merging**
