### PR TITLE
AWS SDK 3 Scripts

### PR DESCRIPTION
**Pull request by augiadam**
Hi Guys,

Sorry for the delay but the update was not as simple as I initially thought. There may still be some functions in the file that I have not checked but the daily backup script works as intended for all functions with SDK 3.

Thanks,

Adam.

### CODE REVIEW

**Comment by dms2015** [comment]
I added root keys instead of smtp and the script worked without all those write to log errors!! You are the bomb!!

What does it mean though that there were no instanceIDs to process below? I am happy that I am finally up to this here without all those errors. I am almost there!

Our Cloud Servers Production Daily Backup Starting
Backup failed; no InstanceIDs to process
Cleaning up daily snapshots
0 daily snapshots deleted
Our Cloud Servers Production Backup Complete

**Comment by noahlh** [comment]
This is awesome - thanks for working on this Adam.  I'll merge now -- if there are any other issues related to the comment above, I'll gladly re-merge.

**Comment by dms2015** [comment]
I am very excited!!  Now, I think it may be just one last simple thing to look over.  Thanks Adam and thanks Noah!!!

Thank you,
 ​
Dawn Stevens

**Comment by augiadam** [comment]
Hi Dawn,

Have you set a tag on your instance(s) to mark them for the backup? In my case I have added a tag called "Snapshot" to the instance I was using for testing and it is working correctly.

capture

I have blanked out anything that might identify my environment but above is what you should see when the script finds an instance with the tag that you define in the DailySnapShot.ps1 $backupTag = "xxxxxxxx"

Thanks,

Adam.

**Comment by dms2015** [comment]
Adam, I tried my instance id and the instance name below where the x is but it still comes back as no instance.  I tried my instance id without the dash also.  The name I put case for case also.  Maybe it is the VPC ID or something else?  Verifying where I got this was on the EC2 Console under Instances.  Is this correct or should it be another place I am getting this instance ID or backup tag?  Thanks for the help!

$backupTag = "xxxxxxxx" #Make sure the value of this Tag is 'Yes', without the quotes, on the instances you want backed up

**Comment by augiadam** [comment]
Hi Dawn,

You need to make a new tag on the instance you want to back up, the instance ID or name will not work. You have to open AWS and select EC2 and then select the Tag menu option and set up a new tag with a value of "Yes". Once you have made the tag you can assign it to all the instances you want to back up and put the name of the tag in that $backupTag ="xxxxxxxx" field.

image

**Comment by dms2015** [comment]
Thank you.  i have everything working now.  :>)  

I have one question:  Snapshots that are to be deleted - are these setup somewhere in one of the scripts?  Right now I have 0 daily snapshots deleted everyday so am I supposed to setup somewhere how many I would like to keep?

**Pull request merged**
